name: Delete PR branch from fork and base repo
'on':
  pull_request:
    types:
    - closed
  pull_request_target:
    types:
    - closed
  workflow_dispatch:
    inputs:
      pull_request_number:
        description: Pull Request number to delete the branch
        required: true
        type: number
jobs:
  delete-branch:
    runs-on: ubuntu-latest
    if: "github.repository_owner == 'wdrx70xn' && (\n  (github.event_name == 'pull_request'\
      \ && github.event.pull_request.merged == false && github.event.sender.login\
      \ == 'roboadhoc') ||\n  (github.event_name == 'pull_request_target' && github.event.pull_request.merged\
      \ == false && github.event.sender.login == 'roboadhoc') ||\n  (github.event_name\
      \ == 'workflow_dispatch') ||\n  (github.event_name == 'deployment_status' &&\
      \  github.event.deployment_status.state == 'success')\n)\n"
    steps:
    - name: Delete branch from base and fork repos
      uses: actions/github-script@v6
      id: pr_data_fetcher
      with:
        script: "// Get PR information\ncore.info('Fetching PR data and validating\
          \ conditions...');\n\n// Debug info\nconst eventName = context.eventName;\n\
          core.info(`El nombre del evento es: ${eventName}`);\ncore.info(JSON.stringify(context,\
          \ null, 2))\n// End Debug info\n\nlet repoOwner = context.repo.owner;\n\
          let repoName = context.repo.repo;\nlet pullRequest;\n\nif (context.eventName\
          \ === 'workflow_dispatch' || context.eventName === 'deployment_status')\
          \ {\n  let prNumber = 0;\n  if (context.eventName === 'workflow_dispatch')\
          \ {\n    prNumber = context.payload.inputs.pull_request_number;\n    core.info(`Manual\
          \ trigger for PR #${prNumber}`);\n  }\n\n  if (context.eventName === 'deployment_status')\
          \ {\n    prNumber = context.payload.deployment_status.description.split(\"\
          #\")[1].split(\" \")[0];\n    core.info(`deployment_status trigger for PR\
          \ #${prNumber}`);\n  }\n\n  // Fetch the PR data using the number\n  pullRequest\
          \ = (await github.rest.pulls.get({\n    owner: repoOwner,\n    repo: repoName,\n\
          \    pull_number: prNumber,\n  })).data;\n\n  core.info(JSON.stringify(pullRequest,\
          \ null, 2))\n\n  if (pullRequest.merged === true) {\n    core.info(`PR #${prNumber}\
          \ was merged. No action needed.`);\n    core.setOutput('validation_passed',\
          \ 'false');\n    return;\n  }\n\n  // Fetch the PR timeline to find the\
          \ 'closed' event\n  const timeline = await github.rest.issues.listEventsForTimeline({\n\
          \    owner: repoOwner,\n    repo: repoName,\n    issue_number: prNumber,\n\
          \  });\n\n  // Find the 'closed' event in the timeline\n  const closeEvent\
          \ = timeline.data.find(event => event.event === 'closed');\n\n  // Get the\
          \ user who closed the PR from the event\n  const closedByLogin = closeEvent\
          \ && closeEvent.actor ? closeEvent.actor.login : null;\n\n  if (closedByLogin\
          \ !== 'roboadhoc') {\n    core.info(`PR #${prNumber} was not closed by 'roboadhoc'\
          \ (${closedByLogin}). No action needed.`);\n    core.setOutput('validation_passed',\
          \ 'false');\n    return;\n  }\n\n} else if (['pull_request', 'pull_request_target'].includes(context.eventName))\
          \ {\n  pullRequest = context.payload.pull_request;\n} else {\n  core.setOutput('validation_passed',\
          \ 'false');\n  core.error(`Unsupported event type: ${context.eventName}`);\n\
          \  return;\n}\n\n// Set outputs for subsequent steps\ncore.setOutput('validation_passed',\
          \ 'true');\ncore.setOutput('base_repo_owner', repoOwner);\ncore.setOutput('base_repo_name',\
          \ repoName);\ncore.setOutput('base_branch_name', pullRequest.head.ref);\n\
          core.setOutput('head_repo_full_name', pullRequest.head.repo.full_name);\n\
          core.setOutput('head_repo_owner', pullRequest.head.repo.owner.login);\n\
          core.setOutput('head_repo_name', pullRequest.head.repo.name);\ncore.setOutput('is_fork',\
          \ pullRequest.head.repo.full_name !== context.repo.owner + '/' + context.repo.repo);\n"
    - name: Delete branch from the base repository
      uses: actions/github-script@v6
      if: ${{ steps.pr_data_fetcher.outputs.validation_passed == 'true' }}
      with:
        github-token: ${{ github.token }}
        script: "const baseBranchName = `${{ steps.pr_data_fetcher.outputs.base_branch_name\
          \ }}`;\nconst baseRepoOwner = `${{ steps.pr_data_fetcher.outputs.base_repo_owner\
          \ }}`;\nconst baseRepoName = `${{ steps.pr_data_fetcher.outputs.base_repo_name\
          \ }}`;\ntry {\n  core.info(`Attempting to delete branch '${baseBranchName}'\
          \ from base repo '${baseRepoOwner}/${baseRepoName}'`);\n  await github.rest.git.deleteRef({\n\
          \    owner: baseRepoOwner,\n    repo: baseRepoName,\n    ref: `heads/${baseBranchName}`,\n\
          \  });\n  core.info(`Branch '${baseBranchName}' deleted from base repo successfully.`);\n\
          } catch (error) {\n  if (error.status === 422) {\n    core.info(`Branch\
          \ '${baseBranchName}' in base repo already deleted. No action needed.`);\n\
          \  } else {\n    console.error(`Error deleting branch '${baseBranchName}'\
          \ from base repo: ${error.message}`);\n  }\n}\n"
    - name: Delete branch from the fork repository (adhoc-dev)
      if: ${{ steps.pr_data_fetcher.outputs.validation_passed == 'true' }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.EXTERNAL_REPO_TOKEN_CLEANER_ADHOC_DEV || github.token
          }}
        script: "const baseBranchName = `${{ steps.pr_data_fetcher.outputs.base_branch_name\
          \ }}`;\nconst headRepoOwner = 'adhoc-dev';\nconst headRepoName = `${{ steps.pr_data_fetcher.outputs.head_repo_name\
          \ }}`;\n\ntry {\n  core.info(`PR comes from a fork. Attempting to delete\
          \ branch from fork repo '${headRepoOwner}/${headRepoName}'`);\n  await github.rest.git.deleteRef({\n\
          \    owner: headRepoOwner,\n    repo: headRepoName,\n    ref: `heads/${baseBranchName}`,\n\
          \  });\n  core.info(`Branch '${baseBranchName}' deleted from fork repo successfully.`);\n\
          } catch (error) {\n  if (error.status === 422) {\n    core.info(`Branch\
          \ '${baseBranchName}' in fork repo already deleted. No action needed.`);\n\
          \  } else {\n    console.error(`Error deleting branch '${baseBranchName}'\
          \ from fork repo: ${error.message}`);\n  }\n}\n"
